### ISSUE TITLE
Compatibility with `gymnasium` possible?

### ISSUE THREAD

**Issue by harmeling** [brett-daley/gym-classics#4]
Right now, when I call the example code:
```
import gym          # version 0.26.2
import gym_classics
env = gym.make('ClassicGridworld-v0')
state = env.reset()

/usr/local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/usr/local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/usr/local/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'int'>`
  logger.warn(
>>> 
```
I will get some warnings.  Possibly this can be resolved by moving from `gym` to `gymnasium`?  However, right now just replacing `gym` by `gymnasium` does not work:
```
import gymnasium as gym
import gym_classics
env = gym.make('ClassicGridworld-v0')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 592, in make
    _check_version_exists(ns, name, version)
  File "/usr/local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 218, in _check_version_exists
    _check_name_exists(ns, name)
  File "/usr/local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 195, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment ClassicGridworld doesn't exist. 
```
My guess is that calling `import gym_classics` will internally call `import gym` and register the environment in the older version, so the environments wont appear in `gymnasium`?

Possible solution: can you check whether `gym` has been already loaded, before loading it yourself in `gym_classics`.  Can that do the trick already?

**Comment by brett-daley** [comment]
That's exactly what's happening, thanks for bringing it to my attention. I think it's a great idea to support the newer Gym API as well as Gymnasium going forward. In the meantime, were you able to find a workaround? You might be able to edit the environment registration [here](https://github.com/brett-daley/gym-classics/blob/36ce6870394be9eaac5f80a4cd0b1de0f21174d8/gym_classics/__init__.py) to use `gymnasium` instead of `gym`, assuming it's backwards compatible.
